### ISSUE TITLE
Not working on Java 17 (Azul OpenJDK, Eclipse Termurin)

### ISSUE THREAD

**Issue by JellyBrick** [jasypt/jasypt#149]
```java
org.jasypt.exceptions.EncryptionOperationNotPossibleException: Encryption raised an exception. A possible cause is you are using strong encryption algorithms and you have not installed the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files in this Java Virtual Machine
    at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.handleInvalidKeyException(StandardPBEByteEncryptor.java:1207)
    at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.encrypt(StandardPBEByteEncryptor.java:996)
    at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.encrypt(StandardPBEStringEncryptor.java:655)
    at org.jasypt.util.text.AES256TextEncryptor.encrypt(AES256TextEncryptor.java:102)


```

**Comment by JellyBrick** [comment]
Using the `setProviderName("SunJCE")` seems to fix it.
